# -*- coding: utf-8 -*-
"""AnalyzingInfectedPatientsDemographics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qqVxtqsxNNzxdzmIEXu-K9A0kmP9aAqm
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

data = data[data["Sex"].isin(["Male","Female"])]

grouped_data = data.groupby(["Sex"])[["Count","Rate"]].sum()

top_diseases = {}
for sex in grouped_data.index:
  subset = data[data["Sex"]==sex]
  subset = subset.drop_duplicates(subset=["Disease"])
  top_diseases[sex] = subset[["Disease","Rate"]].nlargest(5,"Rate")

for sex, top_disease_df in top_diseases.items():
  print(f"Top 5 Diseases for {sex}:")
  print(top_disease_df)

for sex, top_disease_df in top_diseases.items():
  plt.figure(figsize=(10,6))
  plt.barh(top_disease_df["Disease"],top_disease_df["Rate"])
  plt.xlabel("Rate")
  plt.title(f"Top 5 Diseases for {sex}")
  plt.gca().invert_yaxis()
  plt.show()