# -*- coding: utf-8 -*-
"""CleaningInfectiousDiseaseDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UP5Q-Fp8myP3VMQqtUet5orGHso1cBgK
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

missing_values_rows = data.isnull().any(axis=1)
print("Rows with Missing Values:")
print(missing_values_rows)

duplicate_rows = data[data.duplicated()]
print("Duplicate Rows:")
print(duplicate_rows)

data.dropna(axis=0,inplace=True)

data.drop_duplicates(inplace=True)

data.to_csv("cleaned_dataset.csv",index=False)

file_path = "cleaned_dataset.csv"
files.download(file_path)