# -*- coding: utf-8 -*-
"""ConfidenceIntervalAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IAbcMlzYzFweeUXBy7FSEsBNnVDu2mjQ
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

confidence_intervals = data[["CI.lower","CI.upper"]]

confidence_intervals["CI.Width"] = confidence_intervals["CI.upper"] - confidence_intervals["CI.lower"]

average_width = confidence_intervals["CI.Width"].mean()
print(f"Average Width of Confidence Intervals: {average_width}")