# -*- coding: utf-8 -*-
"""DetectingPotentialOutliers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nV32VXmXVE5ewb5DXYaWmjis1D9JQdUI
"""

import pandas as pd
from google.colab import files
import numpy as np

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

columns_to_check = ["Count","Rate"]

outlier_thrshold = 3

# Detect Potential Outliers Count
count_z_score = np.abs((data["Count"]-data["Count"].mean())/data["Count"].std())
count_outlier_mask = count_z_score  > outlier_thrshold
potential_count_outliers = data[count_outlier_mask]
print("Potential Count Outliers:")
print(potential_count_outliers)

# Detecting Potential Outliers Rate
rate_z_score = np.abs((data["Rate"]-data["Rate"].mean())/data["Rate"].std())
rate_outlier_mask = rate_z_score  > outlier_thrshold
potential_rate_outliers = data[rate_outlier_mask]
print("Potential Rate Outliers:")
print(potential_rate_outliers)