# -*- coding: utf-8 -*-
"""FindingCorrelationBetweenPopulation&DiseaseRate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZAoNxvrR_NDDJKB2jqBW205W6BMwdRC
"""

import pandas as pd
from google.colab import files
import matplotlib.pyplot as plt

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

correlation_coefficient = data["Population"].corr(data["Rate"])

print(f'Correlation Coefficient:{correlation_coefficient:.2f}')

plt.figure(figsize=(8,6))
plt.scatter(data["Population"],data["Rate"],alpha=0.5)
plt.xlabel("Population")
plt.ylabel("Disease Rate")
plt.title("Population vs Disease Rate")
plt.text(0.1,0.9,f'Correlation:{correlation_coefficient:.2f}',transform=plt.gca().transAxes)
plt.show()