# -*- coding: utf-8 -*-
"""ForecastingInfectiousDiseaseRatewithTimeSeries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F37075ylawgCDhTzoikKAKhEZNBUCy9V
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from statsmodels.tsa.seasonal import STL

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

count_disease = data["Disease"].nunique()
print(f"Number of Disease: {count_disease}")
print(data["Disease"].value_counts())

data["Year"] = pd.to_datetime(data["Year"],format="%Y")

chlamydia_data = data[data["Disease"] == "Chlamydia"][["Year","Rate"]]

chlamydia_data.set_index("Year",inplace=True)

chlamydia_rate = chlamydia_data["Rate"].values

stl_result  = STL(chlamydia_rate, seasonal=13, period=2).fit()

forecasted_seasonal = stl_result.seasonal[-13:].mean()
forecasted_trend = stl_result.trend[-13:].mean()
forecasted_residual = stl_result.resid[-13:].mean()
forecasted_rate_2015 = forecasted_seasonal + forecasted_trend + forecasted_residual
print(f"Forecasted Chlamydia Rate for 2015: {forecasted_rate_2015}")
stl_result.plot()
plt.show()