# -*- coding: utf-8 -*-
"""InfectiousDiseaseDataOverview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UP5Q-Fp8myP3VMQqtUet5orGHso1cBgK
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

data.info()

data.shape

data.describe()

data.columns

data.dtypes