# -*- coding: utf-8 -*-
"""MappingInfectiousDiseaseperCounty.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12z6Eh1lZR7kyDAquokOj8-3tvjhCy1v7
"""

import matplotlib.pyplot as plt
import pandas as pd
from google.colab import files
import seaborn as sns

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

count_county = data["County"].nunique()
print(f"Number of Counties:{count_county}")

grouped_data = data.groupby(["County","Disease"]).agg({"Count":"sum","Rate":"mean","Population":"mean"}).reset_index()

top_disease_per_county = grouped_data.loc[grouped_data.groupby("County")["Count"].idxmax()]

print(top_disease_per_county[["County","Disease","Count","Rate","Population"]])

heatmap_data = top_disease_per_county.pivot("County","Disease","Count")
plt.figure(figsize=(12,8))
sns.heatmap(heatmap_data, annot = True, fmt=".0f",cmap="YlGnBu",cbar_kws={"label":"Count"})
plt.title("Top Diseases per County")
plt.show()