# -*- coding: utf-8 -*-
"""PublicHealthPolicyEvaluation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTW4zfzFodD-MHZ1BsXmqu3GzZf7MgVl
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("Infectious Disease 2001-2014.csv")

data.head()

disease_name = "Measles"
policy_year = 2009

disease_data = data[data["Disease"]==disease_name]

before_policy = disease_data[disease_data["Year"] < 2009]
after_policy = disease_data[disease_data["Year"] >= 2009]

before_rate = before_policy.groupby("Year")["Rate"].mean()
before_count = before_policy.groupby("Year")["Count"].mean()
after_rate = after_policy.groupby("Year")["Rate"].mean()
after_count = after_policy.groupby("Year")["Count"].mean()

rate_chage = after_rate - before_rate
count_change = after_count - before_count

print("Before Rate:", before_rate)
print("Before Count:", before_count)
print("After Rate:", after_rate)
print("AFter Count:", after_count)
#print("Rate Change:", rate_chage)
#print("Count Change:", count_change)
if(rate_chage < 0).all() and (count_change < 0).all():
  print(f"The public health policy for {disease_name} implemented in {policy_year} has effectiveley decreased  both rate and count")
else:
  print(f"The public health policy for {disease_name} implemented in {policy_year} did not show consistent decrease in rate and count")